name: CI

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Type Check
        run: pnpm tsc --noEmit
      - name: Lint
        run: pnpm lint
